In [4]:
%matplotlib inline
from keras.utils.np_utils import to_categorical
from keras.models import Model,Sequential
from keras.utils.np_utils import to_categorical
from keras.layers import Input, Dense, Dropout
# from keras.optimizers import SGD
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  

In [5]:
data = pd.read_csv("dataset.csv")
data.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [6]:
print(data.shape)
train=[]
for i in range(data.shape[0]):
  train.append(list(data.iloc[i]))

(2000, 21)


In [7]:
x=[]
y=[]
for i in train:
  y.append(i[-1])
  x.append(i[:20])
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=29)


In [8]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)
print(x_train)
print(y_train)

[[1.412e+03 1.000e+00 2.400e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [8.080e+02 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.619e+03 1.000e+00 9.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]
 ...
 [1.872e+03 1.000e+00 2.300e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.133e+03 0.000e+00 1.400e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.242e+03 1.000e+00 2.400e+00 ... 1.000e+00 0.000e+00 0.000e+00]]
[1. 0. 0. ... 2. 1. 0.]


In [9]:
y_train = to_categorical(y_train, 4)
y_test = to_categorical(y_test, 4)
print(y_test)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [14]:
model = Sequential()
model.add(Dense(300, input_dim=x_train.shape[1], activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(150, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(4, activation='softmax'))

model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])


history = model.fit(x_train, y_train,
                    epochs=300,
                    batch_size=32,
                    verbose=1,
                    validation_data=(x_test,y_test))

Epoch 1/300
50/50 [==============================] - 1s 7ms/step - loss: 55.6199 - accuracy: 0.4000 - val_loss: 8.0422 - val_accuracy: 0.4950
Epoch 2/300
50/50 [==============================] - 0s 4ms/step - loss: 16.1548 - accuracy: 0.4137 - val_loss: 4.2592 - val_accuracy: 0.5050
Epoch 3/300
50/50 [==============================] - 0s 5ms/step - loss: 9.1219 - accuracy: 0.4381 - val_loss: 3.1855 - val_accuracy: 0.4525
Epoch 4/300
50/50 [==============================] - 0s 5ms/step - loss: 6.0048 - accuracy: 0.4144 - val_loss: 1.5532 - val_accuracy: 0.4825
Epoch 5/300
50/50 [==============================] - 0s 5ms/step - loss: 3.9143 - accuracy: 0.4131 - val_loss: 1.1127 - val_accuracy: 0.4475
Epoch 6/300
50/50 [==============================] - 0s 5ms/step - loss: 2.5477 - accuracy: 0.4200 - val_loss: 1.1394 - val_accuracy: 0.3725
Epoch 7/300
50/50 [==============================] - 0s 4ms/step - loss: 1.7803 - accuracy: 0.4137 - val_loss: 1.0910 - val_accuracy: 0.3750
Epoch 8/300